@startuml Diagramme de classes
namespace simulateur {
	namespace carte {
		class carte {
			+ taille : int
			+ cases : case[][]
			+ carte()
			+ get_taille() : int
			+ get_cases() : case
			+ get_case(int x, int y) : case
		}
		class case {
			+ type : typeCase
			+ position : position
			+ est_explore : bool
			+ case()
			+ get_type() : typeCase
			+ get_position() : position
		}
		enum typeCase {
			VIDE
			NOURRITURE
			OBSTACLE
			COLONIE
		}

		carte "1" *-- "1..*" case
	}

	namespace colonie {
		class colonie {
			+ colonie(nourriture : float, position : position)
			+ position : position
			+ nourriture : float
			+ fourmis : fourmi[]
			+ get_position() : position
			+ get_nourriture() : int
			+ get_fourmis() : fourmi[]
			+ get_fourmi(int i) : fourmi
			+ ajouter_fourmi(fourmi f) : void
			+ supprimer_fourmi(int i) : void
			+ supprimer_fourmi(fourmi f) : void
			+ ajouter_nourriture(int n) : void
			+ supprimer_nourriture(int n) : void
		}

		namespace fourmi {
			class fourmi {
				+ fourmi()
				+ deplacer() : void
			}
			class reine {
				+ pondre() : void
			}
			class ouvriere {
				+ cherchernourriture() : void
				+ construire() : void
				+ nourrirlarve() : void
				+ pheromone() : void
			}
			class eclaireur {
				+ explorer() : void
			}
			class soldat {
				+ attaquer() : void
			}
			class esclavagiste {
				+ voler() : void
			}

			reine <|-- fourmi
			ouvriere <|-- fourmi
			eclaireur <|-- fourmi
			soldat <|-- fourmi
			esclavagiste <|-- fourmi

		}
	}

}

@enduml